name: rangas
favicon: null
layout_spectrum: 0.76397
typography_spectrum: 0.1898179934360087
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d2cac1'
    - '#010000'
    - '#fbfaf9'
    - '#6c6b6a'
    - '#3e3c39'
  brandStrength: 1
  lightness: 0.6880787080153823
  saturation: 0.5
  rhythmicContrast: 0.8889668169431388
purpose: []
