name: rangas
favicon: null
layout_spectrum: 0.7286374534014612
typography_spectrum: 0.1898179934360087
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.4930716250091791
  lightness: 0.6880787080153823
  saturation: 0.14145711180754006
  rhythmicContrast: 0.8889668169431388
purpose: []
